packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/bun": ^1.3.4
  better-auth: ^1.4.18
  "@tanstack/react-form": ^1.28.0
  "@better-auth/expo": ^1.4.18
