export interface Bus {
	amenities: string[];
	arrivalTime: string;
	departureTime: string;
	duration: string;
	id: string;
	name: string;
	offer?: string;
	originalPrice: number;
	price: number;
	rating: number;
	seatsAvailable: number;
	totalRatings: number;
	type: string;
}

export const DEMO_BUSES: Bus[] = [
	{
		id: "1",
		name: "KBS Travels",
		type: "A/C Sleeper (2+1)",
		departureTime: "21:00",
		arrivalTime: "05:30",
		duration: "8h 30m",
		price: 850,
		originalPrice: 1050,
		rating: 4.5,
		totalRatings: 1174,
		seatsAvailable: 23,
		amenities: ["WiFi", "Charging Point", "Blanket"],
		offer: "Exclusive ₹100 OFF",
	},
	{
		id: "2",
		name: "SRS Travels",
		type: "A/C Seater (2+2)",
		departureTime: "22:15",
		arrivalTime: "06:45",
		duration: "8h 30m",
		price: 620,
		originalPrice: 750,
		rating: 4.2,
		totalRatings: 892,
		seatsAvailable: 15,
		amenities: ["Charging Point", "Water Bottle"],
	},
	{
		id: "3",
		name: "Orange Travels",
		type: "A/C Sleeper (2+1)",
		departureTime: "23:25",
		arrivalTime: "06:20",
		duration: "6h 55m",
		price: 1080,
		originalPrice: 1180,
		rating: 4.8,
		totalRatings: 2341,
		seatsAvailable: 8,
		amenities: ["WiFi", "Charging Point", "Blanket", "Snacks"],
		offer: "Try new 10% OFF",
	},
	{
		id: "4",
		name: "VRL Travels",
		type: "Non A/C Seater (2+3)",
		departureTime: "18:30",
		arrivalTime: "02:00",
		duration: "7h 30m",
		price: 450,
		originalPrice: 450,
		rating: 3.9,
		totalRatings: 567,
		seatsAvailable: 32,
		amenities: ["Water Bottle"],
	},
	{
		id: "5",
		name: "Jabbar Travels",
		type: "A/C Sleeper (2+1)",
		departureTime: "20:00",
		arrivalTime: "04:15",
		duration: "8h 15m",
		price: 920,
		originalPrice: 1100,
		rating: 4.1,
		totalRatings: 743,
		seatsAvailable: 18,
		amenities: ["Charging Point", "Blanket"],
	},
	{
		id: "6",
		name: "Neeta Travels",
		type: "A/C Seater (2+2)",
		departureTime: "06:00",
		arrivalTime: "14:30",
		duration: "8h 30m",
		price: 580,
		originalPrice: 700,
		rating: 4.3,
		totalRatings: 1089,
		seatsAvailable: 20,
		amenities: ["WiFi", "Charging Point"],
	},
	{
		id: "7",
		name: "Kaveri Travels",
		type: "Non A/C Sleeper (2+1)",
		departureTime: "19:45",
		arrivalTime: "03:30",
		duration: "7h 45m",
		price: 520,
		originalPrice: 600,
		rating: 3.7,
		totalRatings: 412,
		seatsAvailable: 28,
		amenities: ["Blanket"],
	},
	{
		id: "8",
		name: "KSRTC Airavat",
		type: "A/C Seater (2+2)",
		departureTime: "23:00",
		arrivalTime: "06:00",
		duration: "7h 00m",
		price: 780,
		originalPrice: 780,
		rating: 4.6,
		totalRatings: 3210,
		seatsAvailable: 5,
		amenities: ["Charging Point", "Water Bottle"],
	},
	{
		id: "9",
		name: "IntrCity SmartBus",
		type: "A/C Sleeper (2+1)",
		departureTime: "21:30",
		arrivalTime: "05:00",
		duration: "7h 30m",
		price: 1250,
		originalPrice: 1500,
		rating: 4.7,
		totalRatings: 1856,
		seatsAvailable: 12,
		amenities: ["WiFi", "Charging Point", "Blanket", "Snacks", "Entertainment"],
		offer: "First Booking 15% OFF",
	},
	{
		id: "10",
		name: "Paulo Travels",
		type: "A/C Sleeper (2+1)",
		departureTime: "22:00",
		arrivalTime: "07:00",
		duration: "9h 00m",
		price: 990,
		originalPrice: 1200,
		rating: 4.4,
		totalRatings: 1523,
		seatsAvailable: 10,
		amenities: ["WiFi", "Charging Point", "Blanket"],
	},
];
